version: '3'

services:
  db:
    image: postgres
  migration:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/app/buyspy
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/buyspy
    ports:
      - "8000:8000"
    depends_on:
      - db
      -migration
