# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('plumbing', models.BooleanField(default=False)),
                ('electrical', models.BooleanField(default=False)),
                ('roofing', models.BooleanField(default=False)),
                ('mold', models.BooleanField(default=False)),
                ('termites', models.BooleanField(default=False)),
                ('basement', models.BooleanField(default=False)),
                ('chimney', models.BooleanField(default=False)),
                ('gutters', models.BooleanField(default=False)),
                ('radon', models.BooleanField(default=False)),
            ],
        ),
    ]
