# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='inspection_file',
            field=models.FileField(default='', upload_to='inspections'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='photo',
            field=models.ImageField(default='', upload_to='inspection_photo'),
            preserve_default=False,
        ),
    ]
