# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_auto_20161016_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='_description_rendered',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='description_markup_type',
            field=models.CharField(blank=True, choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='description',
            field=markupfield.fields.MarkupField(rendered_field=True),
        ),
    ]
